Ogre::D3D11TexturePtr Class Reference - OGRE Documentation
Ogre::D3D11TexturePtr Class Reference
Specialisation of SharedPtr to allow SharedPtr to be assigned to D3D11TexturePtr.
#include <OgreD3D11Texture.h>
Public Member Functions
D3D11TexturePtr ()
D3D11TexturePtr (D3D11Texture *rep)
D3D11TexturePtr (const D3D11TexturePtr &r)
D3D11TexturePtr (const ResourcePtr &r)
D3D11TexturePtr & operator= (const ResourcePtr &r)
Operator used to convert a ResourcePtr to a D3D11TexturePtr.
D3D11TexturePtr & operator= (const TexturePtr &r)
Operator used to convert a TexturePtr to a D3D11TexturePtr.
D3D11Texture & operator* () const
D3D11Texture * operator-> () const
D3D11Texture * get () const
void bind (D3D11Texture *rep, SharedPtrFreeMethod inFreeMethod=SPFM_DELETE)
Binds rep to the SharedPtr.
bool unique () const
unsigned int useCount () const
unsigned int * useCountPointer () const
D3D11Texture * getPointer () const
SharedPtrFreeMethod freeMethod () const
bool isNull (void) const
void setNull (void)
Protected Member Functions
void release (void)
virtual void destroy (void)
virtual void swap (SharedPtr< D3D11Texture > &other)
Protected Attributes
D3D11Texture * pRep
unsigned int * pUseCount
SharedPtrFreeMethod useFreeMethod
Detailed Description
Specialisation of SharedPtr to allow SharedPtr to be assigned to D3D11TexturePtr.
Note:
Has to be a subclass since we need operator=. We could templatise this instead of repeating per Resource subclass, except to do so requires a form VC6 does not support i.e. ResourceSubclassPtr<T> : public SharedPtr<T>
Definition at line 181 of file OgreD3D11Texture.h.
Constructor & Destructor Documentation
Ogre::D3D11TexturePtr::D3D11TexturePtr ()
Definition at line 184 of file OgreD3D11Texture.h.
Ogre::D3D11TexturePtr::D3D11TexturePtr (D3D11Texture * rep) [explicit]
Definition at line 185 of file OgreD3D11Texture.h.
Ogre::D3D11TexturePtr::D3D11TexturePtr (const D3D11TexturePtr & r)
Definition at line 186 of file OgreD3D11Texture.h.
Ogre::D3D11TexturePtr::D3D11TexturePtr (const ResourcePtr & r)
Definition at line 187 of file OgreD3D11Texture.h.
References Ogre::SharedPtr< T >::getPointer(), OGRE_COPY_AUTO_SHARED_MUTEX, OGRE_LOCK_MUTEX, OGRE_MUTEX_CONDITIONAL, Ogre::SharedPtr< D3D11Texture >::pRep, Ogre::SharedPtr< D3D11Texture >::pUseCount, and Ogre::SharedPtr< T >::useCountPointer().
Member Function Documentation
void Ogre::SharedPtr< D3D11Texture >::bind (D3D11Texture * rep, SharedPtrFreeMethod inFreeMethod = SPFM_DELETE) [inherited]
Binds rep to the SharedPtr.
Remarks:
Assumes that the SharedPtr is uninitialised!
Definition at line 167 of file OgreSharedPtr.h.
virtual void Ogre::SharedPtr< D3D11Texture >::destroy (void) [protected, virtual, inherited]
Definition at line 223 of file OgreSharedPtr.h.
SharedPtrFreeMethod Ogre::SharedPtr< D3D11Texture >::freeMethod () const [inherited]
Definition at line 181 of file OgreSharedPtr.h.
D3D11Texture * Ogre::SharedPtr< D3D11Texture >::get (void) const [inherited]
Definition at line 161 of file OgreSharedPtr.h.
D3D11Texture * Ogre::SharedPtr< D3D11Texture >::getPointer () const [inherited]
Definition at line 180 of file OgreSharedPtr.h.
bool Ogre::SharedPtr< D3D11Texture >::isNull (void) const [inherited]
Definition at line 183 of file OgreSharedPtr.h.
D3D11Texture & Ogre::SharedPtr< D3D11Texture >::operator* () const [inherited]
Definition at line 159 of file OgreSharedPtr.h.
D3D11Texture * Ogre::SharedPtr< D3D11Texture >::operator-> () const [inherited]
Definition at line 160 of file OgreSharedPtr.h.
D3D11TexturePtr& Ogre::D3D11TexturePtr::operator= (const ResourcePtr & r)
Operator used to convert a ResourcePtr to a D3D11TexturePtr.
Definition at line 204 of file OgreD3D11Texture.h.
References Ogre::SharedPtr< T >::getPointer(), OGRE_COPY_AUTO_SHARED_MUTEX, OGRE_LOCK_MUTEX, OGRE_MUTEX_CONDITIONAL, Ogre::SharedPtr< D3D11Texture >::pRep, Ogre::SharedPtr< D3D11Texture >::pUseCount, Ogre::SharedPtr< D3D11Texture >::release(), and Ogre::SharedPtr< T >::useCountPointer().
D3D11TexturePtr& Ogre::D3D11TexturePtr::operator= (const TexturePtr & r)
Operator used to convert a TexturePtr to a D3D11TexturePtr.
Definition at line 224 of file OgreD3D11Texture.h.
References Ogre::SharedPtr< T >::getPointer(), OGRE_COPY_AUTO_SHARED_MUTEX, OGRE_LOCK_MUTEX, OGRE_MUTEX_CONDITIONAL, Ogre::SharedPtr< D3D11Texture >::pRep, Ogre::SharedPtr< D3D11Texture >::pUseCount, Ogre::SharedPtr< D3D11Texture >::release(), and Ogre::SharedPtr< T >::useCountPointer().
void Ogre::SharedPtr< D3D11Texture >::release (void) [protected, inherited]
Definition at line 197 of file OgreSharedPtr.h.
Referenced by operator=().
void Ogre::SharedPtr< D3D11Texture >::setNull (void) [inherited]
Definition at line 185 of file OgreSharedPtr.h.
virtual void Ogre::SharedPtr< D3D11Texture >::swap (SharedPtr< D3D11Texture > & other) [protected, virtual, inherited]
Definition at line 247 of file OgreSharedPtr.h.
bool Ogre::SharedPtr< D3D11Texture >::unique () const [inherited]
Definition at line 176 of file OgreSharedPtr.h.
unsigned int Ogre::SharedPtr< D3D11Texture >::useCount () const [inherited]
Definition at line 177 of file OgreSharedPtr.h.
unsigned int* Ogre::SharedPtr< D3D11Texture >::useCountPointer () const [inherited]
Definition at line 178 of file OgreSharedPtr.h.
Member Data Documentation
D3D11Texture * Ogre::SharedPtr< D3D11Texture >::pRep [protected, inherited]
Definition at line 63 of file OgreSharedPtr.h.
Referenced by D3D11TexturePtr(), and operator=().
unsigned int* Ogre::SharedPtr< D3D11Texture >::pUseCount [protected, inherited]
Definition at line 64 of file OgreSharedPtr.h.
Referenced by D3D11TexturePtr(), and operator=().
SharedPtrFreeMethod Ogre::SharedPtr< D3D11Texture >::useFreeMethod [protected, inherited]
Definition at line 65 of file OgreSharedPtr.h.
The documentation for this class was generated from the following file:
OgreD3D11Texture.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Sun Sep 2 2012 07:27:47