Ogre::SmallVector< T, N > Class Template Reference - OGRE Documentation
Ogre::SmallVector< T, N > Class Template Reference
SmallVector - This is a 'vector' (really, a variable-sized array), optimized for the case when the array is small.
#include <OgreSmallVector.h>
Public Types
typedef SuperClass::iterator iterator
typedef SuperClass::size_type size_type
typedef ptrdiff_t difference_type
typedef T value_type
typedef const T * const_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
Public Member Functions
SmallVector ()
SmallVector (unsigned Size, const T &Value=T())
template<typename ItTy >
SmallVector (ItTy S, ItTy E)
SmallVector (const SmallVector &RHS)
const SmallVector & operator= (const SmallVector &RHS)
void clear ()
void resize (unsigned N)
void resize (unsigned N, const T &NV)
void reserve (unsigned N)
void push_back (const T &Elt)
void pop_back ()
T pop_back_val ()
void swap (SmallVectorImpl &RHS)
template<typename in_iter >
void append (in_iter in_start, in_iter in_end)
append - Add the specified range to the end of the SmallVector.
void append (size_type NumInputs, const T &Elt)
append - Add the specified range to the end of the SmallVector.
void assign (unsigned NumElts, const T &Elt)
iterator erase (iterator I)
iterator erase (iterator S, iterator E)
iterator insert (iterator I, const T &Elt)
iterator insert (iterator I, size_type NumToInsert, const T &Elt)
template<typename ItTy >
iterator insert (iterator I, ItTy From, ItTy To)
bool operator== (const SmallVectorImpl &RHS) const
bool operator!= (const SmallVectorImpl &RHS) const
bool operator< (const SmallVectorImpl &RHS) const
void set_size (unsigned N)
set_size - Set the array size to
void grow (size_t MinSize=0)
grow - double the size of the allocated memory, guaranteeing space for at least one more element or MinSize if specified.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size () const
size_type max_size () const
size_t capacity () const
capacity - Return the total number of elements in the currently allocated buffer.
pointer data ()
data - Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
data - Return a pointer to the vector's buffer, even if empty().
reference operator[] (unsigned idx)
const_reference operator[] (unsigned idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
bool empty () const
Static Public Member Functions
static void destroy_range (T *S, T *E)
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
uninitialized_copy - Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Protected Member Functions
void setEnd (T *P)
iterator capacity_ptr ()
const_iterator capacity_ptr () const
bool isSmall () const
isSmall - Return true if this is a smallvector which has not had dynamic memory allocated for it.
size_t size_in_bytes () const
size_in_bytes - This returns size()*sizeof(T).
size_t capacity_in_bytes () const
capacity_in_bytes - This returns capacity()*sizeof(T).
void grow_pod (size_t MinSizeInBytes, size_t TSize)
grow_pod - This is an implementation of the grow() method which only works
Protected Attributes
void * BeginX
void * EndX
void * CapacityX
union Ogre::SmallVectorBase::U FirstEl
Private Types
enum { MinUs }
typedef SmallVectorImpl< T >::U U
InlineElts - These are 'N-1' elements that are stored inline in the body of the vector.
Private Attributes
U InlineElts [NumInlineEltsElts]
Detailed Description
template<typename T, unsigned N>
class Ogre::SmallVector< T, N >
SmallVector - This is a 'vector' (really, a variable-sized array), optimized for the case when the array is small.
It contains some number of elements in-place, which allows it to avoid heap allocation when the actual number of elements is below that threshold. This allows normal "small" cases to be fast without losing generality for large inputs.
Note that this does not attempt to be exception safe.
Definition at line 717 of file OgreSmallVector.h.
Member Typedef Documentation
template<typename T> typedef const T* Ogre::SmallVectorTemplateCommon< T >::const_iterator [inherited]
Definition at line 173 of file OgreSmallVector.h.
template<typename T> typedef const T* Ogre::SmallVectorTemplateCommon< T >::const_pointer [inherited]
Definition at line 181 of file OgreSmallVector.h.
template<typename T> typedef const T& Ogre::SmallVectorTemplateCommon< T >::const_reference [inherited]
Definition at line 179 of file OgreSmallVector.h.
template<typename T> typedef std::reverse_iterator<const_iterator> Ogre::SmallVectorTemplateCommon< T >::const_reverse_iterator [inherited]
Definition at line 175 of file OgreSmallVector.h.
template<typename T> typedef ptrdiff_t Ogre::SmallVectorTemplateCommon< T >::difference_type [inherited]
Definition at line 170 of file OgreSmallVector.h.
template<typename T> typedef SuperClass::iterator Ogre::SmallVectorImpl< T >::iterator [inherited]
Reimplemented from Ogre::SmallVectorTemplateCommon< T >.
Definition at line 332 of file OgreSmallVector.h.
template<typename T> typedef T* Ogre::SmallVectorTemplateCommon< T >::pointer [inherited]
Definition at line 180 of file OgreSmallVector.h.
template<typename T> typedef T& Ogre::SmallVectorTemplateCommon< T >::reference [inherited]
Definition at line 178 of file OgreSmallVector.h.
template<typename T> typedef std::reverse_iterator<iterator> Ogre::SmallVectorTemplateCommon< T >::reverse_iterator [inherited]
Definition at line 176 of file OgreSmallVector.h.
template<typename T> typedef SuperClass::size_type Ogre::SmallVectorImpl< T >::size_type [inherited]
Reimplemented from Ogre::SmallVectorTemplateCommon< T >.
Definition at line 333 of file OgreSmallVector.h.
template<typename T, unsigned N> typedef SmallVectorImpl<T>::U Ogre::SmallVector< T, N >::U [private]
InlineElts - These are 'N-1' elements that are stored inline in the body of the vector.
The extra '1' element is stored in SmallVectorImpl.
Definition at line 720 of file OgreSmallVector.h.
template<typename T> typedef T Ogre::SmallVectorTemplateCommon< T >::value_type [inherited]
Definition at line 171 of file OgreSmallVector.h.
Member Enumeration Documentation
template<typename T, unsigned N> anonymous enum [private]
Enumerator:
MinUs
Definition at line 721 of file OgreSmallVector.h.
Constructor & Destructor Documentation
template<typename T, unsigned N> Ogre::SmallVector< T, N >::SmallVector ()
Definition at line 739 of file OgreSmallVector.h.
template<typename T, unsigned N> Ogre::SmallVector< T, N >::SmallVector (unsigned Size, const T & Value = T()) [explicit]
Definition at line 742 of file OgreSmallVector.h.
template<typename T, unsigned N> template<typename ItTy > Ogre::SmallVector< T, N >::SmallVector (ItTy S, ItTy E)
Definition at line 750 of file OgreSmallVector.h.
template<typename T, unsigned N> Ogre::SmallVector< T, N >::SmallVector (const SmallVector< T, N > & RHS)
Definition at line 754 of file OgreSmallVector.h.
Member Function Documentation
template<typename T> template<typename in_iter > void Ogre::SmallVectorImpl< T >::append (in_iter in_start, in_iter in_end) [inherited]
append - Add the specified range to the end of the SmallVector.
Definition at line 411 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::insert(), Ogre::SmallVector< PMTriangle *, 8 >::SmallVector(), and Ogre::SmallVector< T, 0 >::SmallVector().
template<typename T> void Ogre::SmallVectorImpl< T >::append (size_type NumInputs, const T & Elt) [inherited]
append - Add the specified range to the end of the SmallVector.
Definition at line 426 of file OgreSmallVector.h.
template<typename T> void Ogre::SmallVectorImpl< T >::assign (unsigned NumElts, const T & Elt) [inherited]
Definition at line 436 of file OgreSmallVector.h.
template<typename T> reference Ogre::SmallVectorTemplateCommon< T >::back () [inherited]
Definition at line 227 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::insert(), and Ogre::SmallVectorImpl< PMVertex * >::pop_back_val().
template<typename T> const_reference Ogre::SmallVectorTemplateCommon< T >::back () const [inherited]
Definition at line 230 of file OgreSmallVector.h.
template<typename T> iterator Ogre::SmallVectorTemplateCommon< T >::begin () [inherited]
Definition at line 184 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::assign(), Ogre::SmallVectorTemplateCommon< PMVertex * >::capacity(), Ogre::SmallVectorImpl< PMVertex * >::clear(), Ogre::SmallVectorTemplateCommon< PMVertex * >::data(), Ogre::SmallVectorTemplateCommon< PMVertex * >::front(), Ogre::SmallVectorImpl< PMVertex * >::insert(), Ogre::SmallVectorImpl< PMVertex * >::operator<(), Ogre::SmallVectorImpl< T >::operator=(), Ogre::SmallVectorImpl< PMVertex * >::operator==(), Ogre::SmallVectorTemplateCommon< PMVertex * >::operator[](), Ogre::SmallVectorTemplateCommon< PMVertex * >::rend(), Ogre::SmallVectorImpl< PMVertex * >::resize(), Ogre::SmallVectorImpl< PMVertex * >::set_size(), Ogre::SmallVectorTemplateCommon< PMVertex * >::size(), Ogre::SmallVectorImpl< T >::swap(), and Ogre::SmallVectorImpl< PMVertex * >::~SmallVectorImpl().
template<typename T> const_iterator Ogre::SmallVectorTemplateCommon< T >::begin () const [inherited]
Definition at line 185 of file OgreSmallVector.h.
template<typename T> size_t Ogre::SmallVectorTemplateCommon< T >::capacity () const [inherited]
capacity - Return the total number of elements in the currently allocated buffer.
Definition at line 204 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::assign(), Ogre::SmallVectorImpl< PMVertex * >::reserve(), Ogre::SmallVectorImpl< PMVertex * >::resize(), Ogre::SmallVectorImpl< PMVertex * >::set_size(), and Ogre::SmallVectorImpl< T >::swap().
size_t Ogre::SmallVectorBase::capacity_in_bytes () const [protected, inherited]
capacity_in_bytes - This returns capacity()*sizeof(T).
Definition at line 149 of file OgreSmallVector.h.
References Ogre::SmallVectorBase::BeginX, and Ogre::SmallVectorBase::CapacityX.
template<typename T> iterator Ogre::SmallVectorTemplateCommon< T >::capacity_ptr () [protected, inherited]
Definition at line 189 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::append(), and Ogre::SmallVectorTemplateCommon< PMVertex * >::capacity().
template<typename T> const_iterator Ogre::SmallVectorTemplateCommon< T >::capacity_ptr () const [protected, inherited]
Definition at line 190 of file OgreSmallVector.h.
template<typename T> void Ogre::SmallVectorImpl< T >::clear (void) [inherited]
Definition at line 350 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::assign().
template<typename T> pointer Ogre::SmallVectorTemplateCommon< T >::data () [inherited]
data - Return a pointer to the vector's buffer, even if empty().
Definition at line 207 of file OgreSmallVector.h.
template<typename T> const_pointer Ogre::SmallVectorTemplateCommon< T >::data () const [inherited]
data - Return a pointer to the vector's buffer, even if empty().
Definition at line 209 of file OgreSmallVector.h.
static void Ogre::SmallVectorTemplateBase< T, isPodLike >::destroy_range (T * S, T * E) [static, inherited]
Definition at line 242 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::clear(), Ogre::SmallVectorImpl< PMVertex * >::erase(), Ogre::SmallVectorImpl< PMVertex * >::resize(), and Ogre::SmallVectorImpl< PMVertex * >::~SmallVectorImpl().
bool Ogre::SmallVectorBase::empty () const [inherited]
Definition at line 158 of file OgreSmallVector.h.
References Ogre::SmallVectorBase::BeginX, and Ogre::SmallVectorBase::EndX.
Referenced by Ogre::SmallVector< PMTriangle *, 8 >::SmallVector().
template<typename T> iterator Ogre::SmallVectorTemplateCommon< T >::end (void) [inherited]
Definition at line 186 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::append(), Ogre::SmallVectorImpl< PMVertex * >::assign(), Ogre::SmallVectorTemplateCommon< PMVertex * >::back(), Ogre::SmallVectorImpl< PMVertex * >::clear(), Ogre::SmallVectorImpl< PMVertex * >::erase(), Ogre::SmallVectorImpl< PMVertex * >::insert(), Ogre::SmallVectorImpl< PMVertex * >::operator<(), Ogre::SmallVectorImpl< T >::operator=(), Ogre::SmallVectorImpl< PMVertex * >::operator==(), Ogre::SmallVectorTemplateCommon< PMVertex * >::operator[](), Ogre::SmallVectorImpl< PMVertex * >::pop_back(), Ogre::SmallVectorImpl< PMVertex * >::push_back(), Ogre::SmallVectorTemplateCommon< PMVertex * >::rbegin(), Ogre::SmallVectorImpl< PMVertex * >::resize(), Ogre::SmallVectorTemplateCommon< PMVertex * >::size(), Ogre::SmallVectorImpl< T >::swap(), and Ogre::SmallVectorImpl< PMVertex * >::~SmallVectorImpl().
template<typename T> const_iterator Ogre::SmallVectorTemplateCommon< T >::end (void) const [inherited]
Definition at line 187 of file OgreSmallVector.h.
template<typename T> iterator Ogre::SmallVectorImpl< T >::erase (iterator I) [inherited]
Definition at line 444 of file OgreSmallVector.h.
template<typename T> iterator Ogre::SmallVectorImpl< T >::erase (iterator S, iterator E) [inherited]
Definition at line 453 of file OgreSmallVector.h.
template<typename T> reference Ogre::SmallVectorTemplateCommon< T >::front () [inherited]
Definition at line 220 of file OgreSmallVector.h.
template<typename T> const_reference Ogre::SmallVectorTemplateCommon< T >::front () const [inherited]
Definition at line 223 of file OgreSmallVector.h.
void Ogre::SmallVectorTemplateBase< T, isPodLike >::grow (size_t MinSize = 0) [inherited]
grow - double the size of the allocated memory, guaranteeing space for at least one more element or MinSize if specified.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::append(), Ogre::SmallVectorImpl< PMVertex * >::assign(), Ogre::SmallVectorImpl< PMVertex * >::insert(), Ogre::SmallVectorImpl< PMVertex * >::push_back(), Ogre::SmallVectorImpl< PMVertex * >::reserve(), Ogre::SmallVectorImpl< PMVertex * >::resize(), and Ogre::SmallVectorImpl< T >::swap().
void Ogre::SmallVectorBase::grow_pod (size_t MinSizeInBytes, size_t TSize) [protected, inherited]
grow_pod - This is an implementation of the grow() method which only works
on POD-like data types and is out of line to reduce code duplication.
Referenced by Ogre::SmallVectorTemplateBase< T, true >::grow().
template<typename T> iterator Ogre::SmallVectorImpl< T >::insert (iterator I, const T & Elt) [inherited]
Definition at line 463 of file OgreSmallVector.h.
template<typename T> iterator Ogre::SmallVectorImpl< T >::insert (iterator I, size_type NumToInsert, const T & Elt) [inherited]
Definition at line 484 of file OgreSmallVector.h.
template<typename T> template<typename ItTy > iterator Ogre::SmallVectorImpl< T >::insert (iterator I, ItTy From, ItTy To) [inherited]
Definition at line 532 of file OgreSmallVector.h.
bool Ogre::SmallVectorBase::isSmall () const [protected, inherited]
isSmall - Return true if this is a smallvector which has not had dynamic memory allocated for it.
Definition at line 139 of file OgreSmallVector.h.
References Ogre::SmallVectorBase::BeginX, and Ogre::SmallVectorBase::FirstEl.
Referenced by Ogre::SmallVectorImpl< T >::swap(), and Ogre::SmallVectorImpl< PMVertex * >::~SmallVectorImpl().
template<typename T> size_type Ogre::SmallVectorTemplateCommon< T >::max_size () const [inherited]
Definition at line 200 of file OgreSmallVector.h.
template<typename T> bool Ogre::SmallVectorImpl< T >::operator!= (const SmallVectorImpl< T > & RHS) const [inherited]
Definition at line 590 of file OgreSmallVector.h.
template<typename T> bool Ogre::SmallVectorImpl< T >::operator< (const SmallVectorImpl< T > & RHS) const [inherited]
Definition at line 594 of file OgreSmallVector.h.
template<typename T, unsigned N> const SmallVector& Ogre::SmallVector< T, N >::operator= (const SmallVector< T, N > & RHS)
Definition at line 759 of file OgreSmallVector.h.
Referenced by Ogre::SmallVector< PMTriangle *, 8 >::operator=(), Ogre::SmallVector< T, 0 >::operator=(), and Ogre::SmallVector< T, 0 >::SmallVector().
template<typename T> bool Ogre::SmallVectorImpl< T >::operator== (const SmallVectorImpl< T > & RHS) const [inherited]
Definition at line 586 of file OgreSmallVector.h.
template<typename T> reference Ogre::SmallVectorTemplateCommon< T >::operator[] (unsigned idx) [inherited]
Definition at line 211 of file OgreSmallVector.h.
template<typename T> const_reference Ogre::SmallVectorTemplateCommon< T >::operator[] (unsigned idx) const [inherited]
Definition at line 215 of file OgreSmallVector.h.
template<typename T> void Ogre::SmallVectorImpl< T >::pop_back () [inherited]
Definition at line 395 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::erase(), and Ogre::SmallVectorImpl< PMVertex * >::pop_back_val().
template<typename T> T Ogre::SmallVectorImpl< T >::pop_back_val () [inherited]
Definition at line 400 of file OgreSmallVector.h.
template<typename T> void Ogre::SmallVectorImpl< T >::push_back (const T & Elt) [inherited]
Definition at line 384 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::insert(), Ogre::SmallVector< PMTriangle *, 8 >::SmallVector(), and Ogre::SmallVector< T, 0 >::SmallVector().
template<typename T> reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rbegin () [inherited]
Definition at line 194 of file OgreSmallVector.h.
template<typename T> const_reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rbegin () const [inherited]
Definition at line 195 of file OgreSmallVector.h.
template<typename T> reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rend () [inherited]
Definition at line 196 of file OgreSmallVector.h.
template<typename T> const_reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rend () const [inherited]
Definition at line 197 of file OgreSmallVector.h.
template<typename T> void Ogre::SmallVectorImpl< T >::reserve (unsigned N) [inherited]
Definition at line 379 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::insert(), Ogre::SmallVector< PMTriangle *, 8 >::SmallVector(), and Ogre::SmallVector< T, 0 >::SmallVector().
template<typename T> void Ogre::SmallVectorImpl< T >::resize (unsigned N) [inherited]
Definition at line 355 of file OgreSmallVector.h.
template<typename T> void Ogre::SmallVectorImpl< T >::resize (unsigned N, const T & NV) [inherited]
Definition at line 367 of file OgreSmallVector.h.
template<typename T> void Ogre::SmallVectorImpl< T >::set_size (unsigned N) [inherited]
set_size - Set the array size to
N, which the current array must have enough capacity for.
This does not construct or destroy any elements in the vector.
Clients can use this in conjunction with capacity() to write past the end of the buffer when they know that more elements are available, and only update the size later. This avoids the cost of value initializing elements which will only be overwritten.
Definition at line 608 of file OgreSmallVector.h.
template<typename T> void Ogre::SmallVectorTemplateCommon< T >::setEnd (T * P) [protected, inherited]
Definition at line 165 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::append(), Ogre::SmallVectorImpl< PMVertex * >::assign(), Ogre::SmallVectorImpl< PMVertex * >::erase(), Ogre::SmallVectorImpl< PMVertex * >::insert(), Ogre::SmallVectorImpl< PMVertex * >::pop_back(), Ogre::SmallVectorImpl< PMVertex * >::push_back(), Ogre::SmallVectorImpl< PMVertex * >::resize(), Ogre::SmallVectorImpl< PMVertex * >::set_size(), and Ogre::SmallVectorImpl< T >::swap().
template<typename T> size_type Ogre::SmallVectorTemplateCommon< T >::size (void) const [inherited]
Definition at line 199 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::append(), Ogre::SmallVectorImpl< PMVertex * >::insert(), Ogre::SmallVectorImpl< T >::operator=(), Ogre::SmallVectorImpl< PMVertex * >::operator==(), Ogre::SmallVectorImpl< PMVertex * >::resize(), and Ogre::SmallVectorImpl< T >::swap().
size_t Ogre::SmallVectorBase::size_in_bytes () const [protected, inherited]
size_in_bytes - This returns size()*sizeof(T).
Definition at line 144 of file OgreSmallVector.h.
References Ogre::SmallVectorBase::BeginX, and Ogre::SmallVectorBase::EndX.
template<typename T > void Ogre::SmallVectorImpl< T >::swap (SmallVectorImpl< T > & RHS) [inherited]
Definition at line 622 of file OgreSmallVector.h.
References Ogre::SmallVectorTemplateCommon< T >::begin(), Ogre::SmallVectorBase::BeginX, Ogre::SmallVectorTemplateCommon< T >::capacity(), Ogre::SmallVectorBase::CapacityX, Ogre::SmallVectorTemplateCommon< T >::end(), Ogre::SmallVectorBase::EndX, Ogre::SmallVectorTemplateBase< T, isPodLike< T >::value >::grow(), Ogre::SmallVectorBase::isSmall(), Ogre::SmallVectorTemplateCommon< T >::setEnd(), Ogre::SmallVectorTemplateCommon< T >::size(), and std::swap().
Referenced by std::swap().
static void Ogre::SmallVectorTemplateBase< T, isPodLike >::uninitialized_copy (It1 I, It1 E, It2 Dest) [static, inherited]
uninitialized_copy - Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Definition at line 252 of file OgreSmallVector.h.
References Ogre::SmallVectorTemplateBase< T, isPodLike >::uninitialized_copy().
Referenced by Ogre::SmallVectorImpl< PMVertex * >::append(), and Ogre::SmallVectorImpl< PMVertex * >::insert().
Member Data Documentation
void* Ogre::SmallVectorBase::BeginX [protected, inherited]
Definition at line 118 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorTemplateCommon< PMVertex * >::begin(), Ogre::SmallVectorBase::capacity_in_bytes(), Ogre::SmallVectorImpl< PMVertex * >::clear(), Ogre::SmallVectorBase::empty(), Ogre::SmallVectorBase::isSmall(), Ogre::SmallVectorBase::size_in_bytes(), and Ogre::SmallVectorImpl< T >::swap().
void * Ogre::SmallVectorBase::CapacityX [protected, inherited]
Definition at line 118 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorBase::capacity_in_bytes(), Ogre::SmallVectorTemplateCommon< PMVertex * >::capacity_ptr(), Ogre::SmallVectorImpl< PMVertex * >::insert(), Ogre::SmallVectorImpl< PMVertex * >::push_back(), and Ogre::SmallVectorImpl< T >::swap().
void * Ogre::SmallVectorBase::EndX [protected, inherited]
Definition at line 118 of file OgreSmallVector.h.
Referenced by Ogre::SmallVectorImpl< PMVertex * >::clear(), Ogre::SmallVectorBase::empty(), Ogre::SmallVectorTemplateCommon< PMVertex * >::end(), Ogre::SmallVectorTemplateCommon< PMVertex * >::setEnd(), Ogre::SmallVectorBase::size_in_bytes(), and Ogre::SmallVectorImpl< T >::swap().
union Ogre::SmallVectorBase::U Ogre::SmallVectorBase::FirstEl [protected, inherited]
Referenced by Ogre::SmallVectorBase::isSmall().
template<typename T, unsigned N> U Ogre::SmallVector< T, N >::InlineElts[NumInlineEltsElts] [private]
Definition at line 737 of file OgreSmallVector.h.
The documentation for this class was generated from the following file:
OgreSmallVector.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Sun Sep 2 2012 07:27:40