Ogre::D3D9HardwarePixelBuffer Class Reference - OGRE Documentation
Ogre::D3D9HardwarePixelBuffer Class Reference
#include <OgreD3D9HardwarePixelBuffer.h>
Classes
struct BufferResources
Public Types
enum Usage {
HBU_STATIC = 1, HBU_DYNAMIC = 2, HBU_WRITE_ONLY = 4, HBU_DISCARDABLE = 8,
HBU_STATIC_WRITE_ONLY = 5, HBU_DYNAMIC_WRITE_ONLY = 6, HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE = 14
}
Enums describing buffer usage; not mutually exclusive.
enum LockOptions { HBL_NORMAL, HBL_DISCARD, HBL_READ_ONLY, HBL_NO_OVERWRITE }
Locking options.
Public Member Functions
D3D9HardwarePixelBuffer (HardwareBuffer::Usage usage, D3D9Texture *ownerTexture)
~D3D9HardwarePixelBuffer ()
void bind (IDirect3DDevice9 *dev, IDirect3DSurface9 *mSurface, IDirect3DSurface9 *fsaaSurface, bool writeGamma, uint fsaa, const String &srcName, IDirect3DBaseTexture9 *mipTex)
Call this to associate a D3D surface or volume with this pixel buffer.
void bind (IDirect3DDevice9 *dev, IDirect3DVolume9 *mVolume, IDirect3DBaseTexture9 *mipTex)
void blit (const HardwarePixelBufferSharedPtr &src, const Image::Box &srcBox, const Image::Box &dstBox)
void blitFromMemory (const PixelBox &src, const Image::Box &dstBox)
void blitToMemory (const Image::Box &srcBox, const PixelBox &dst)
void _genMipmaps (IDirect3DBaseTexture9 *mipTex)
Internal function to update mipmaps on update of level 0.
void _setMipmapping (bool doMipmapGen, bool HWMipmaps)
Function to set mipmap generation.
RenderTexture * getRenderTarget (size_t zoffset)
Get rendertarget for z slice.
IDirect3DSurface9 * getSurface (IDirect3DDevice9 *d3d9Device)
Accessor for surface.
IDirect3DSurface9 * getFSAASurface (IDirect3DDevice9 *d3d9Device)
Accessor for AA surface.
virtual void _clearSliceRTT (size_t zoffset)
Notify TextureBuffer of destruction of render target.
void releaseSurfaces (IDirect3DDevice9 *d3d9Device)
Release surfaces held by this pixel buffer.
void destroyBufferResources (IDirect3DDevice9 *d3d9Device)
Destroy resources associated with the given device.
virtual const PixelBox & lock (const Image::Box &lockBox, LockOptions options)
Lock the buffer for (potentially) reading / writing.
virtual void * lock (size_t offset, size_t length, LockOptions options)
void * lock (LockOptions options)
Lock the entire buffer for (potentially) reading / writing.
const PixelBox & getCurrentLock ()
Get the current locked region.
virtual void readData (size_t offset, size_t length, void *pDest)
virtual void writeData (size_t offset, size_t length, const void *pSource, bool discardWholeBuffer=false)
void blit (const HardwarePixelBufferSharedPtr &src)
Convenience function that blits the entire source pixel buffer to this buffer.
void blitFromMemory (const PixelBox &src)
Convenience function that blits a pixelbox from memory to the entire buffer.
void blitToMemory (const PixelBox &dst)
Convience function that blits this entire buffer to a pixelbox.
size_t getWidth () const
Gets the width of this buffer.
size_t getHeight () const
Gets the height of this buffer.
size_t getDepth () const
Gets the depth of this buffer.
PixelFormat getFormat () const
Gets the native pixel format of this buffer.
virtual void unlock (void)
Releases the lock on this buffer.
virtual void copyData (HardwareBuffer &srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer=false)
Copy data from another buffer into this one.
virtual void copyData (HardwareBuffer &srcBuffer)
Copy all data from another buffer into this one.
virtual void _updateFromShadow (void)
Updates the real buffer from the shadow buffer, if required.
size_t getSizeInBytes (void) const
Returns the size of this buffer in bytes.
Usage getUsage (void) const
Returns the Usage flags with which this buffer was created.
bool isSystemMemory (void) const
Returns whether this buffer is held in system memory.
bool hasShadowBuffer (void) const
Returns whether this buffer has a system memory shadow for quicker reading.
bool isLocked (void) const
Returns whether or not this buffer is currently locked.
void suppressHardwareUpdate (bool suppress)
Pass true to suppress hardware upload of shadow buffer changes.
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
Static Public Member Functions
static void lockDeviceAccess ()
static void unlockDeviceAccess ()
Protected Types
typedef map< IDirect3DDevice9
*, BufferResources * >::type DeviceToBufferResourcesMap
typedef
DeviceToBufferResourcesMap::iterator DeviceToBufferResourcesIterator
Protected Member Functions
PixelBox lockImpl (const Image::Box lockBox, LockOptions options)
Lock a box.
PixelBox lockBuffer (BufferResources *bufferResources, const Image::Box &lockBox, DWORD flags)
void unlockImpl (void)
Unlock a box.
void unlockBuffer (BufferResources *bufferResources)
BufferResources * getBufferResources (IDirect3DDevice9 *d3d9Device)
BufferResources * createBufferResources ()
void updateRenderTexture (bool writeGamma, uint fsaa, const String &srcName)
updates render texture.
void destroyRenderTexture ()
destroy render texture.
void blit (IDirect3DDevice9 *d3d9Device, const HardwarePixelBufferSharedPtr &src, const Image::Box &srcBox, const Image::Box &dstBox, BufferResources *srcBufferResources, BufferResources *dstBufferResources)
void blitFromMemory (const PixelBox &src, const Image::Box &dstBox, BufferResources *dstBufferResources)
void blitToMemory (const Image::Box &srcBox, const PixelBox &dst, BufferResources *srcBufferResources, IDirect3DDevice9 *d3d9Device)
virtual void * lockImpl (size_t offset, size_t length, LockOptions options)
Internal implementation of lock(), do not OVERRIDE or CALL this for HardwarePixelBuffer implementations, but override the previous method.
Protected Attributes
DeviceToBufferResourcesMap mMapDeviceToBufferResources
Map between device to buffer resources.
bool mDoMipmapGen
Mipmapping.
bool mHWMipmaps
D3D9RenderTexture * mRenderTexture
Render target.
D3D9Texture * mOwnerTexture
DWORD mLockFlags
size_t mWidth
size_t mHeight
size_t mDepth
size_t mRowPitch
size_t mSlicePitch
PixelFormat mFormat
PixelBox mCurrentLock
Image::Box mLockedBox
size_t mSizeInBytes
Usage mUsage
bool mIsLocked
size_t mLockStart
size_t mLockSize
bool mSystemMemory
bool mUseShadowBuffer
HardwareBuffer * mShadowBuffer
bool mShadowUpdated
bool mSuppressHardwareUpdate
Friends
class RenderTexture
Detailed Description
Definition at line 39 of file OgreD3D9HardwarePixelBuffer.h.
Member Typedef Documentation
typedef DeviceToBufferResourcesMap::iterator Ogre::D3D9HardwarePixelBuffer::DeviceToBufferResourcesIterator [protected]
Definition at line 59 of file OgreD3D9HardwarePixelBuffer.h.
typedef map<IDirect3DDevice9*, BufferResources*>::type Ogre::D3D9HardwarePixelBuffer::DeviceToBufferResourcesMap [protected]
Definition at line 58 of file OgreD3D9HardwarePixelBuffer.h.
Member Enumeration Documentation
enum Ogre::HardwareBuffer::LockOptions [inherited]
Locking options.
Enumerator:
HBL_NORMAL
Normal mode, ie allows read/write and contents are preserved.
HBL_DISCARD
Discards the entire buffer while locking; this allows optimisation to be performed because synchronisation issues are relaxed.
Only allowed on buffers created with the HBU_DYNAMIC flag.
HBL_READ_ONLY
Lock the buffer for reading only.
Not allowed in buffers which are created with HBU_WRITE_ONLY. Mandatory on static buffers, i.e. those created without the HBU_DYNAMIC flag.
HBL_NO_OVERWRITE
As HBL_NORMAL, except the application guarantees not to overwrite any region of the buffer which has already been used in this frame, can allow some optimisation on some APIs.
Definition at line 121 of file OgreHardwareBuffer.h.
enum Ogre::HardwareBuffer::Usage [inherited]
Enums describing buffer usage; not mutually exclusive.
Enumerator:
HBU_STATIC
Static buffer which the application rarely modifies once created.
Modifying the contents of this buffer will involve a performance hit.
HBU_DYNAMIC
Indicates the application would like to modify this buffer with the CPU fairly often.
Buffers created with this flag will typically end up in AGP memory rather than video memory.
HBU_WRITE_ONLY
Indicates the application will never read the contents of the buffer back, it will only ever write data.
Locking a buffer with this flag will ALWAYS return a pointer to new, blank memory rather than the memory associated with the contents of the buffer; this avoids DMA stalls because you can write to a new memory area while the previous one is being used.
HBU_DISCARDABLE
Indicates that the application will be refilling the contents of the buffer regularly (not just updating, but generating the contents from scratch), and therefore does not mind if the contents of the buffer are lost somehow and need to be recreated.
This allows and additional level of optimisation on the buffer. This option only really makes sense when combined with HBU_DYNAMIC_WRITE_ONLY.
HBU_STATIC_WRITE_ONLY
Combination of HBU_STATIC and HBU_WRITE_ONLY.
HBU_DYNAMIC_WRITE_ONLY
Combination of HBU_DYNAMIC and HBU_WRITE_ONLY.
If you use this, strongly consider using HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE instead if you update the entire contents of the buffer very regularly.
HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE
Combination of HBU_DYNAMIC, HBU_WRITE_ONLY and HBU_DISCARDABLE.
Definition at line 79 of file OgreHardwareBuffer.h.
Constructor & Destructor Documentation
Ogre::D3D9HardwarePixelBuffer::D3D9HardwarePixelBuffer (HardwareBuffer::Usage usage, D3D9Texture * ownerTexture)
Ogre::D3D9HardwarePixelBuffer::~D3D9HardwarePixelBuffer ()
Member Function Documentation
virtual void Ogre::D3D9HardwarePixelBuffer::_clearSliceRTT (size_t zoffset) [virtual]
Notify TextureBuffer of destruction of render target.
Reimplemented from Ogre::HardwarePixelBuffer.
void Ogre::D3D9HardwarePixelBuffer::_genMipmaps (IDirect3DBaseTexture9 * mipTex)
Internal function to update mipmaps on update of level 0.
void Ogre::D3D9HardwarePixelBuffer::_setMipmapping (bool doMipmapGen, bool HWMipmaps)
Function to set mipmap generation.
virtual void Ogre::HardwareBuffer::_updateFromShadow (void) [virtual, inherited]
Updates the real buffer from the shadow buffer, if required.
Reimplemented in Ogre::GLESHardwareVertexBuffer, Ogre::GLES2HardwareVertexBuffer, Ogre::GLESHardwareIndexBuffer, Ogre::GLES2HardwareIndexBuffer, Ogre::GLHardwareVertexBuffer, and Ogre::GLHardwareIndexBuffer.
Definition at line 303 of file OgreHardwareBuffer.h.
void Ogre::D3D9HardwarePixelBuffer::bind (IDirect3DDevice9 * dev, IDirect3DSurface9 * mSurface, IDirect3DSurface9 * fsaaSurface, bool writeGamma, uint fsaa, const String & srcName, IDirect3DBaseTexture9 * mipTex)
Call this to associate a D3D surface or volume with this pixel buffer.
void Ogre::D3D9HardwarePixelBuffer::bind (IDirect3DDevice9 * dev, IDirect3DVolume9 * mVolume, IDirect3DBaseTexture9 * mipTex)
void Ogre::D3D9HardwarePixelBuffer::blit (IDirect3DDevice9 * d3d9Device, const HardwarePixelBufferSharedPtr & src, const Image::Box & srcBox, const Image::Box & dstBox, BufferResources * srcBufferResources, BufferResources * dstBufferResources) [protected]
void Ogre::D3D9HardwarePixelBuffer::blit (const HardwarePixelBufferSharedPtr & src, const Image::Box & srcBox, const Image::Box & dstBox) [virtual]
Copies a box from another PixelBuffer to a region of the this PixelBuffer.
Parameters:
dst Source pixel buffer
srcBox Image::Box describing the source region in src
dstBox Image::Box describing the destination region in this buffer
Remarks:
The source and destination regions dimensions don't have to match, in which case scaling is done. This scaling is generally done using a bilinear filter in hardware, but it is faster to pass the source image in the right dimensions.
Note:
Only call this function when both buffers are unlocked.
Reimplemented from Ogre::HardwarePixelBuffer.
void Ogre::HardwarePixelBuffer::blit (const HardwarePixelBufferSharedPtr & src) [inherited]
Convenience function that blits the entire source pixel buffer to this buffer.
If source and destination dimensions don't match, scaling is done.
Parameters:
src PixelBox containing the source pixels and format in memory
Note:
Only call this function when the buffer is unlocked.
void Ogre::D3D9HardwarePixelBuffer::blitFromMemory (const PixelBox & src, const Image::Box & dstBox, BufferResources * dstBufferResources) [protected]
void Ogre::D3D9HardwarePixelBuffer::blitFromMemory (const PixelBox & src, const Image::Box & dstBox) [virtual]
Copies a region from normal memory to a region of this pixelbuffer.
The source image can be in any pixel format supported by OGRE, and in any size.
Parameters:
src PixelBox containing the source pixels and format in memory
dstBox Image::Box describing the destination region in this buffer
Remarks:
The source and destination regions dimensions don't have to match, in which case scaling is done. This scaling is generally done using a bilinear filter in hardware, but it is faster to pass the source image in the right dimensions.
Note:
Only call this function when the buffer is unlocked.
Implements Ogre::HardwarePixelBuffer.
void Ogre::HardwarePixelBuffer::blitFromMemory (const PixelBox & src) [inherited]
Convenience function that blits a pixelbox from memory to the entire buffer.
The source image is scaled as needed.
Parameters:
src PixelBox containing the source pixels and format in memory
Note:
Only call this function when the buffer is unlocked.
Definition at line 151 of file OgreHardwarePixelBuffer.h.
void Ogre::D3D9HardwarePixelBuffer::blitToMemory (const Image::Box & srcBox, const PixelBox & dst, BufferResources * srcBufferResources, IDirect3DDevice9 * d3d9Device) [protected]
void Ogre::D3D9HardwarePixelBuffer::blitToMemory (const Image::Box & srcBox, const PixelBox & dst) [virtual]
Copies a region of this pixelbuffer to normal memory.
Parameters:
srcBox Image::Box describing the source region of this buffer
dst PixelBox describing the destination pixels and format in memory
Remarks:
The source and destination regions don't have to match, in which case scaling is done.
Note:
Only call this function when the buffer is unlocked.
Implements Ogre::HardwarePixelBuffer.
void Ogre::HardwarePixelBuffer::blitToMemory (const PixelBox & dst) [inherited]
Convience function that blits this entire buffer to a pixelbox.
The image is scaled as needed.
Parameters:
src PixelBox containing the source pixels and format in memory
Note:
Only call this function when the buffer is unlocked.
Definition at line 170 of file OgreHardwarePixelBuffer.h.
virtual void Ogre::HardwareBuffer::copyData (HardwareBuffer & srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer = false) [virtual, inherited]
Copy data from another buffer into this one.
Remarks:
Note that the source buffer must not be created with the usage HBU_WRITE_ONLY otherwise this will fail.
Parameters:
srcBuffer The buffer from which to read the copied data
srcOffset Offset in the source buffer at which to start reading
dstOffset Offset in the destination buffer to start writing
length Length of the data to copy, in bytes.
discardWholeBuffer If true, will discard the entire contents of this buffer before copying
Reimplemented in Ogre::D3D11HardwareBuffer, Ogre::D3D11HardwareIndexBuffer, and Ogre::D3D11HardwareVertexBuffer.
Definition at line 282 of file OgreHardwareBuffer.h.
References Ogre::HardwareBuffer::lock(), and Ogre::HardwareBuffer::unlock().
virtual void Ogre::HardwareBuffer::copyData (HardwareBuffer & srcBuffer) [virtual, inherited]
Copy all data from another buffer into this one.
Remarks:
Normally these buffers should be of identical size, but if they're not, the routine will use the smallest of the two sizes.
Definition at line 296 of file OgreHardwareBuffer.h.
References Ogre::HardwareBuffer::getSizeInBytes().
BufferResources* Ogre::D3D9HardwarePixelBuffer::createBufferResources () [protected]
void Ogre::D3D9HardwarePixelBuffer::destroyBufferResources (IDirect3DDevice9 * d3d9Device)
Destroy resources associated with the given device.
void Ogre::D3D9HardwarePixelBuffer::destroyRenderTexture () [protected]
destroy render texture.
BufferResources* Ogre::D3D9HardwarePixelBuffer::getBufferResources (IDirect3DDevice9 * d3d9Device) [protected]
const PixelBox& Ogre::HardwarePixelBuffer::getCurrentLock () [inherited]
Get the current locked region.
This is the same value as returned by lock(const Image::Box, LockOptions)
Returns:
PixelBox containing the locked region
size_t Ogre::HardwarePixelBuffer::getDepth () const [inherited]
Gets the depth of this buffer.
Definition at line 189 of file OgreHardwarePixelBuffer.h.
PixelFormat Ogre::HardwarePixelBuffer::getFormat () const [inherited]
Gets the native pixel format of this buffer.
Definition at line 191 of file OgreHardwarePixelBuffer.h.
IDirect3DSurface9* Ogre::D3D9HardwarePixelBuffer::getFSAASurface (IDirect3DDevice9 * d3d9Device)
Accessor for AA surface.
size_t Ogre::HardwarePixelBuffer::getHeight () const [inherited]
Gets the height of this buffer.
Definition at line 187 of file OgreHardwarePixelBuffer.h.
RenderTexture* Ogre::D3D9HardwarePixelBuffer::getRenderTarget (size_t zoffset) [virtual]
Get rendertarget for z slice.
Reimplemented from Ogre::HardwarePixelBuffer.
size_t Ogre::HardwareBuffer::getSizeInBytes (void) const [inherited]
Returns the size of this buffer in bytes.
Definition at line 328 of file OgreHardwareBuffer.h.
Referenced by Ogre::HardwareBuffer::copyData().
IDirect3DSurface9* Ogre::D3D9HardwarePixelBuffer::getSurface (IDirect3DDevice9 * d3d9Device)
Accessor for surface.
Usage Ogre::HardwareBuffer::getUsage (void) const [inherited]
Returns the Usage flags with which this buffer was created.
Definition at line 330 of file OgreHardwareBuffer.h.
size_t Ogre::HardwarePixelBuffer::getWidth () const [inherited]
Gets the width of this buffer.
Definition at line 185 of file OgreHardwarePixelBuffer.h.
bool Ogre::HardwareBuffer::hasShadowBuffer (void) const [inherited]
Returns whether this buffer has a system memory shadow for quicker reading.
Definition at line 334 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::isLocked (void) const [inherited]
Returns whether or not this buffer is currently locked.
Reimplemented in Ogre::D3D11HardwareIndexBuffer, and Ogre::D3D11HardwareVertexBuffer.
Definition at line 336 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::isSystemMemory (void) const [inherited]
Returns whether this buffer is held in system memory.
Definition at line 332 of file OgreHardwareBuffer.h.
virtual const PixelBox& Ogre::HardwarePixelBuffer::lock (const Image::Box & lockBox, LockOptions options) [virtual, inherited]
Lock the buffer for (potentially) reading / writing.
Parameters:
lockBox Region of the buffer to lock
options Locking options
Returns:
PixelBox containing the locked region, the pitches and the pixel format
virtual void* Ogre::HardwarePixelBuffer::lock (size_t offset, size_t length, LockOptions options) [virtual, inherited]
Lock the buffer for (potentially) reading / writing.
Parameters:
offset The byte offset from the start of the buffer to lock
length The size of the area to lock, in bytes
options Locking options
Returns:
Pointer to the locked memory
Reimplemented from Ogre::HardwareBuffer.
void* Ogre::HardwareBuffer::lock (LockOptions options) [inherited]
Lock the entire buffer for (potentially) reading / writing.
Parameters:
options Locking options
Returns:
Pointer to the locked memory
Definition at line 218 of file OgreHardwareBuffer.h.
PixelBox Ogre::D3D9HardwarePixelBuffer::lockBuffer (BufferResources * bufferResources, const Image::Box & lockBox, DWORD flags) [protected]
static void Ogre::D3D9HardwarePixelBuffer::lockDeviceAccess () [static]
virtual void* Ogre::HardwarePixelBuffer::lockImpl (size_t offset, size_t length, LockOptions options) [protected, virtual, inherited]
Internal implementation of lock(), do not OVERRIDE or CALL this for HardwarePixelBuffer implementations, but override the previous method.
Implements Ogre::HardwareBuffer.
PixelBox Ogre::D3D9HardwarePixelBuffer::lockImpl (const Image::Box lockBox, LockOptions options) [protected, virtual]
Lock a box.
Implements Ogre::HardwarePixelBuffer.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) [inherited]
Definition at line 95 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) [inherited]
Definition at line 101 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) [inherited]
Definition at line 107 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) [inherited]
Definition at line 112 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) [inherited]
Definition at line 118 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) [inherited]
operator new, with debug line info
Definition at line 67 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) [inherited]
Definition at line 72 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) [inherited]
placement operator new
Definition at line 78 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) [inherited]
array operator new, with debug line info
Definition at line 85 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) [inherited]
Definition at line 90 of file OgreMemoryAllocatedObject.h.
virtual void Ogre::HardwarePixelBuffer::readData (size_t offset, size_t length, void * pDest) [virtual, inherited]
Reads data from the buffer and places it in the memory pointed to by pDest.
Parameters:
offset The byte offset from the start of the buffer to read
length The size of the area to read, in bytes
pDest The area of memory in which to place the data, must be large enough to accommodate the data!
Implements Ogre::HardwareBuffer.
void Ogre::D3D9HardwarePixelBuffer::releaseSurfaces (IDirect3DDevice9 * d3d9Device)
Release surfaces held by this pixel buffer.
void Ogre::HardwareBuffer::suppressHardwareUpdate (bool suppress) [inherited]
Pass true to suppress hardware upload of shadow buffer changes.
Definition at line 340 of file OgreHardwareBuffer.h.
virtual void Ogre::HardwareBuffer::unlock (void) [virtual, inherited]
Releases the lock on this buffer.
Remarks:
Locking and unlocking a buffer can, in some rare circumstances such as switching video modes whilst the buffer is locked, corrupt the contents of a buffer. This is pretty rare, but if it occurs, this method will throw an exception, meaning you must re-upload the data.
Note that using the 'read' and 'write' forms of updating the buffer does not suffer from this problem, so if you want to be 100% sure your data will not be lost, use the 'read' and 'write' forms instead.
Reimplemented in Ogre::DefaultHardwareIndexBuffer, Ogre::GLDefaultHardwareIndexBuffer, Ogre::GLESDefaultHardwareIndexBuffer, Ogre::GLES2DefaultHardwareIndexBuffer, Ogre::DefaultHardwareVertexBuffer, Ogre::GLDefaultHardwareVertexBuffer, Ogre::GLESDefaultHardwareVertexBuffer, Ogre::GLES2DefaultHardwareVertexBuffer, Ogre::D3D11HardwareIndexBuffer, and Ogre::D3D11HardwareVertexBuffer.
Definition at line 234 of file OgreHardwareBuffer.h.
Referenced by Ogre::HardwareBuffer::copyData().
void Ogre::D3D9HardwarePixelBuffer::unlockBuffer (BufferResources * bufferResources) [protected]
static void Ogre::D3D9HardwarePixelBuffer::unlockDeviceAccess () [static]
void Ogre::D3D9HardwarePixelBuffer::unlockImpl (void) [protected, virtual]
Unlock a box.
Implements Ogre::HardwareBuffer.
void Ogre::D3D9HardwarePixelBuffer::updateRenderTexture (bool writeGamma, uint fsaa, const String & srcName) [protected]
updates render texture.
virtual void Ogre::HardwarePixelBuffer::writeData (size_t offset, size_t length, const void * pSource, bool discardWholeBuffer = false) [virtual, inherited]
Writes data to the buffer from an area of system memory; note that you must ensure that your buffer is big enough.
Parameters:
offset The byte offset from the start of the buffer to start writing
length The size of the data to write to, in bytes
pSource The source of the data to be written
discardWholeBuffer If true, this allows the driver to discard the entire buffer when writing, such that DMA stalls can be avoided; use if you can.
Implements Ogre::HardwareBuffer.
Friends And Related Function Documentation
friend class RenderTexture [friend, inherited]
Definition at line 81 of file OgreHardwarePixelBuffer.h.
Member Data Documentation
PixelBox Ogre::HardwarePixelBuffer::mCurrentLock [protected, inherited]
Reimplemented in Ogre::D3D11HardwarePixelBuffer.
Definition at line 62 of file OgreHardwarePixelBuffer.h.
size_t Ogre::HardwarePixelBuffer::mDepth [protected, inherited]
Definition at line 56 of file OgreHardwarePixelBuffer.h.
bool Ogre::D3D9HardwarePixelBuffer::mDoMipmapGen [protected]
Mipmapping.
Definition at line 65 of file OgreD3D9HardwarePixelBuffer.h.
PixelFormat Ogre::HardwarePixelBuffer::mFormat [protected, inherited]
Definition at line 60 of file OgreHardwarePixelBuffer.h.
size_t Ogre::HardwarePixelBuffer::mHeight [protected, inherited]
Definition at line 56 of file OgreHardwarePixelBuffer.h.
bool Ogre::D3D9HardwarePixelBuffer::mHWMipmaps [protected]
Definition at line 66 of file OgreD3D9HardwarePixelBuffer.h.
bool Ogre::HardwareBuffer::mIsLocked [protected, inherited]
Definition at line 143 of file OgreHardwareBuffer.h.
Image::Box Ogre::HardwarePixelBuffer::mLockedBox [protected, inherited]
Definition at line 64 of file OgreHardwarePixelBuffer.h.
DWORD Ogre::D3D9HardwarePixelBuffer::mLockFlags [protected]
Definition at line 75 of file OgreD3D9HardwarePixelBuffer.h.
size_t Ogre::HardwareBuffer::mLockSize [protected, inherited]
Definition at line 145 of file OgreHardwareBuffer.h.
size_t Ogre::HardwareBuffer::mLockStart [protected, inherited]
Definition at line 144 of file OgreHardwareBuffer.h.
DeviceToBufferResourcesMap Ogre::D3D9HardwarePixelBuffer::mMapDeviceToBufferResources [protected]
Map between device to buffer resources.
Definition at line 62 of file OgreD3D9HardwarePixelBuffer.h.
D3D9Texture* Ogre::D3D9HardwarePixelBuffer::mOwnerTexture [protected]
Definition at line 72 of file OgreD3D9HardwarePixelBuffer.h.
D3D9RenderTexture* Ogre::D3D9HardwarePixelBuffer::mRenderTexture [protected]
Render target.
Definition at line 69 of file OgreD3D9HardwarePixelBuffer.h.
size_t Ogre::HardwarePixelBuffer::mRowPitch [protected, inherited]
Definition at line 58 of file OgreHardwarePixelBuffer.h.
HardwareBuffer* Ogre::HardwareBuffer::mShadowBuffer [protected, inherited]
Definition at line 148 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::mShadowUpdated [protected, inherited]
Definition at line 149 of file OgreHardwareBuffer.h.
size_t Ogre::HardwareBuffer::mSizeInBytes [protected, inherited]
Definition at line 141 of file OgreHardwareBuffer.h.
size_t Ogre::HardwarePixelBuffer::mSlicePitch [protected, inherited]
Definition at line 58 of file OgreHardwarePixelBuffer.h.
bool Ogre::HardwareBuffer::mSuppressHardwareUpdate [protected, inherited]
Definition at line 150 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::mSystemMemory [protected, inherited]
Definition at line 146 of file OgreHardwareBuffer.h.
Usage Ogre::HardwareBuffer::mUsage [protected, inherited]
Definition at line 142 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::mUseShadowBuffer [protected, inherited]
Definition at line 147 of file OgreHardwareBuffer.h.
size_t Ogre::HardwarePixelBuffer::mWidth [protected, inherited]
Definition at line 56 of file OgreHardwarePixelBuffer.h.
The documentation for this class was generated from the following file:
OgreD3D9HardwarePixelBuffer.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Sun Sep 2 2012 07:27:48