Ogre::AnyNumeric Class Reference - OGRE Documentation
Ogre::AnyNumeric Class Reference
General
Specialised Any class which has built in arithmetic operators, but can hold only types which support operator +,-,* and / .
#include <OgreAny.h>
Classes
class numholder
class numplaceholder
Public Member Functions
AnyNumeric ()
template<typename ValueType >
AnyNumeric (const ValueType &value)
AnyNumeric (const AnyNumeric &other)
AnyNumeric & operator= (const AnyNumeric &rhs)
AnyNumeric operator+ (const AnyNumeric &rhs) const
AnyNumeric operator- (const AnyNumeric &rhs) const
AnyNumeric operator* (const AnyNumeric &rhs) const
AnyNumeric operator* (Real factor) const
AnyNumeric operator/ (const AnyNumeric &rhs) const
AnyNumeric & operator+= (const AnyNumeric &rhs)
AnyNumeric & operator-= (const AnyNumeric &rhs)
AnyNumeric & operator*= (const AnyNumeric &rhs)
AnyNumeric & operator/= (const AnyNumeric &rhs)
Any & swap (Any &rhs)
bool isEmpty () const
const std::type_info & getType () const
void destroy ()
template<typename ValueType >
ValueType operator() () const
template<typename ValueType >
ValueType get (void) const
Protected Member Functions
AnyNumeric (placeholder *pholder)
Construct from holder.
Protected Attributes
placeholder * mContent
Friends
std::ostream & operator<< (std::ostream &o, const Any &v)
template<typename ValueType >
ValueType * any_cast (Any *)
Detailed Description
Specialised Any class which has built in arithmetic operators, but can hold only types which support operator +,-,* and / .
Definition at line 247 of file OgreAny.h.
Constructor & Destructor Documentation
Ogre::AnyNumeric::AnyNumeric ()
Definition at line 250 of file OgreAny.h.
Referenced by operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), and operator=().
template<typename ValueType > Ogre::AnyNumeric::AnyNumeric (const ValueType & value)
Definition at line 256 of file OgreAny.h.
References Ogre::Any::mContent, Ogre::MEMCATEGORY_GENERAL, and OGRE_NEW_T.
Ogre::AnyNumeric::AnyNumeric (const AnyNumeric & other)
Definition at line 262 of file OgreAny.h.
References Ogre::Any::placeholder::clone(), and Ogre::Any::mContent.
Ogre::AnyNumeric::AnyNumeric (placeholder * pholder) [protected]
Construct from holder.
Definition at line 337 of file OgreAny.h.
References Ogre::Any::mContent.
Member Function Documentation
void Ogre::Any::destroy () [inherited]
Definition at line 122 of file OgreAny.h.
References Ogre::Any::mContent, Ogre::MEMCATEGORY_GENERAL, and OGRE_DELETE_T.
Referenced by Ogre::Any::~Any().
template<typename ValueType > ValueType Ogre::Any::get (void) const [inherited]
Definition at line 218 of file OgreAny.h.
References Ogre::Exception::ERR_INVALIDPARAMS, Ogre::Any::getType(), and Ogre::Any::mContent.
const std::type_info& Ogre::Any::getType (void) const [inherited]
Definition at line 109 of file OgreAny.h.
References Ogre::Any::placeholder::getType(), and Ogre::Any::mContent.
Referenced by Ogre::any_cast(), Ogre::Any::get(), and Ogre::Any::operator()().
bool Ogre::Any::isEmpty () const [inherited]
Definition at line 104 of file OgreAny.h.
References Ogre::Any::mContent.
template<typename ValueType > ValueType Ogre::Any::operator() () const [inherited]
Definition at line 194 of file OgreAny.h.
References Ogre::Exception::ERR_INVALIDPARAMS, Ogre::Any::getType(), and Ogre::Any::mContent.
AnyNumeric Ogre::AnyNumeric::operator* (const AnyNumeric & rhs) const
Definition at line 358 of file OgreAny.h.
References AnyNumeric(), and Ogre::Any::mContent.
AnyNumeric Ogre::AnyNumeric::operator* (Real factor) const
Definition at line 363 of file OgreAny.h.
References AnyNumeric(), and Ogre::Any::mContent.
AnyNumeric& Ogre::AnyNumeric::operator*= (const AnyNumeric & rhs)
Definition at line 385 of file OgreAny.h.
References AnyNumeric(), and Ogre::Any::mContent.
AnyNumeric Ogre::AnyNumeric::operator+ (const AnyNumeric & rhs) const
Definition at line 348 of file OgreAny.h.
References AnyNumeric(), and Ogre::Any::mContent.
AnyNumeric& Ogre::AnyNumeric::operator+= (const AnyNumeric & rhs)
Definition at line 373 of file OgreAny.h.
References AnyNumeric(), and Ogre::Any::mContent.
AnyNumeric Ogre::AnyNumeric::operator- (const AnyNumeric & rhs) const
Definition at line 353 of file OgreAny.h.
References AnyNumeric(), and Ogre::Any::mContent.
AnyNumeric& Ogre::AnyNumeric::operator-= (const AnyNumeric & rhs)
Definition at line 379 of file OgreAny.h.
References AnyNumeric(), and Ogre::Any::mContent.
AnyNumeric Ogre::AnyNumeric::operator/ (const AnyNumeric & rhs) const
Definition at line 368 of file OgreAny.h.
References AnyNumeric(), and Ogre::Any::mContent.
AnyNumeric& Ogre::AnyNumeric::operator/= (const AnyNumeric & rhs)
Definition at line 391 of file OgreAny.h.
References AnyNumeric(), and Ogre::Any::mContent.
AnyNumeric& Ogre::AnyNumeric::operator= (const AnyNumeric & rhs)
Definition at line 343 of file OgreAny.h.
References AnyNumeric().
Any& Ogre::Any::swap (Any & rhs) [inherited]
Definition at line 83 of file OgreAny.h.
References Ogre::Any::mContent.
Friends And Related Function Documentation
template<typename ValueType > ValueType* any_cast (Any * operand) [friend, inherited]
Definition at line 405 of file OgreAny.h.
std::ostream& operator<< (std::ostream & o, const Any & v) [friend, inherited]
Definition at line 115 of file OgreAny.h.
Member Data Documentation
placeholder* Ogre::Any::mContent [protected, inherited]
Definition at line 185 of file OgreAny.h.
Referenced by Ogre::any_cast(), AnyNumeric(), Ogre::Any::destroy(), Ogre::Any::get(), Ogre::Any::getType(), Ogre::Any::isEmpty(), Ogre::Any::operator()(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), and Ogre::Any::swap().
The documentation for this class was generated from the following file:
OgreAny.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Sun Sep 2 2012 07:27:25