Ogre::Degree Class Reference - OGRE Documentation
Ogre::Degree Class Reference
Math
Wrapper class which indicates a given angle value is in Degrees.
#include <OgreMath.h>
Public Member Functions
Degree (Real d=0)
Degree (const Radian &r)
Degree & operator= (const Real &f)
Degree & operator= (const Degree &d)
Degree & operator= (const Radian &r)
Real valueDegrees () const
Real valueRadians () const
Real valueAngleUnits () const
const Degree & operator+ () const
Degree operator+ (const Degree &d) const
Degree operator+ (const Radian &r) const
Degree & operator+= (const Degree &d)
Degree & operator+= (const Radian &r)
Degree operator- () const
Degree operator- (const Degree &d) const
Degree operator- (const Radian &r) const
Degree & operator-= (const Degree &d)
Degree & operator-= (const Radian &r)
Degree operator* (Real f) const
Degree operator* (const Degree &f) const
Degree & operator*= (Real f)
Degree operator/ (Real f) const
Degree & operator/= (Real f)
bool operator< (const Degree &d) const
bool operator<= (const Degree &d) const
bool operator== (const Degree &d) const
bool operator!= (const Degree &d) const
bool operator>= (const Degree &d) const
bool operator> (const Degree &d) const
Private Attributes
Real mDeg
Friends
_OgreExport friend std::ostream & operator<< (std::ostream &o, const Degree &v)
Detailed Description
Wrapper class which indicates a given angle value is in Degrees.
Remarks:
Degree values are interchangeable with Radian values, and conversions will be done automatically between them.
Definition at line 97 of file OgreMath.h.
Constructor & Destructor Documentation
Ogre::Degree::Degree (Real d = 0) [explicit]
Definition at line 102 of file OgreMath.h.
Referenced by operator*(), operator+(), operator-(), and operator/().
Ogre::Degree::Degree (const Radian & r)
Definition at line 103 of file OgreMath.h.
Member Function Documentation
bool Ogre::Degree::operator!= (const Degree & d) const
Definition at line 131 of file OgreMath.h.
References mDeg.
Degree Ogre::Degree::operator* (Real f) const
Definition at line 122 of file OgreMath.h.
References Degree(), and mDeg.
Degree Ogre::Degree::operator* (const Degree & f) const
Definition at line 123 of file OgreMath.h.
References Degree(), and mDeg.
Degree& Ogre::Degree::operator*= (Real f)
Definition at line 124 of file OgreMath.h.
References mDeg.
const Degree& Ogre::Degree::operator+ () const
Definition at line 112 of file OgreMath.h.
Degree Ogre::Degree::operator+ (const Degree & d) const
Definition at line 113 of file OgreMath.h.
References Degree(), and mDeg.
Degree Ogre::Degree::operator+ (const Radian & r) const
Definition at line 114 of file OgreMath.h.
References Degree(), mDeg, and Ogre::Radian::valueDegrees().
Degree& Ogre::Degree::operator+= (const Degree & d)
Definition at line 115 of file OgreMath.h.
References mDeg.
Degree& Ogre::Degree::operator+= (const Radian & r)
Definition at line 116 of file OgreMath.h.
References mDeg, and Ogre::Radian::valueDegrees().
Degree Ogre::Degree::operator- () const
Definition at line 117 of file OgreMath.h.
References Degree(), and mDeg.
Degree Ogre::Degree::operator- (const Degree & d) const
Definition at line 118 of file OgreMath.h.
References Degree(), and mDeg.
Degree Ogre::Degree::operator- (const Radian & r) const
Definition at line 119 of file OgreMath.h.
References Degree(), mDeg, and Ogre::Radian::valueDegrees().
Degree& Ogre::Degree::operator-= (const Degree & d)
Definition at line 120 of file OgreMath.h.
References mDeg.
Degree& Ogre::Degree::operator-= (const Radian & r)
Definition at line 121 of file OgreMath.h.
References mDeg, and Ogre::Radian::valueDegrees().
Degree Ogre::Degree::operator/ (Real f) const
Definition at line 125 of file OgreMath.h.
References Degree(), and mDeg.
Degree& Ogre::Degree::operator/= (Real f)
Definition at line 126 of file OgreMath.h.
References mDeg.
bool Ogre::Degree::operator< (const Degree & d) const
Definition at line 128 of file OgreMath.h.
References mDeg.
bool Ogre::Degree::operator<= (const Degree & d) const
Definition at line 129 of file OgreMath.h.
References mDeg.
Degree& Ogre::Degree::operator= (const Real & f)
Definition at line 104 of file OgreMath.h.
References mDeg.
Degree& Ogre::Degree::operator= (const Degree & d)
Definition at line 105 of file OgreMath.h.
References mDeg.
Degree& Ogre::Degree::operator= (const Radian & r)
Definition at line 106 of file OgreMath.h.
References mDeg, and Ogre::Radian::valueDegrees().
bool Ogre::Degree::operator== (const Degree & d) const
Definition at line 130 of file OgreMath.h.
References mDeg.
bool Ogre::Degree::operator> (const Degree & d) const
Definition at line 133 of file OgreMath.h.
References mDeg.
bool Ogre::Degree::operator>= (const Degree & d) const
Definition at line 132 of file OgreMath.h.
References mDeg.
Real Ogre::Degree::valueDegrees () const
Definition at line 108 of file OgreMath.h.
References mDeg.
Referenced by Ogre::Math::Abs(), Ogre::operator*(), Ogre::operator/(), Ogre::Math::Sign(), and Ogre::Math::Sqrt().
Friends And Related Function Documentation
_OgreExport friend std::ostream& operator<< (std::ostream & o, const Degree & v) [friend]
Definition at line 136 of file OgreMath.h.
Member Data Documentation
Real Ogre::Degree::mDeg [private]
Definition at line 99 of file OgreMath.h.
Referenced by operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), valueAngleUnits(), valueDegrees(), and valueRadians().
The documentation for this class was generated from the following file:
OgreMath.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Sun Sep 2 2012 07:27:30