Ogre::ConstVectorRange< T > Struct Template Reference - OGRE Documentation
Ogre::ConstVectorRange< T > Struct Template Reference
Predefined type.
#include <OgreIteratorRange.h>
Public Types
typedef T iterator
typedef to fulfill container interface
typedef T const_iterator
typedef to fulfill container interface
typedef iterator_range< T > type
defines the real used type
Public Member Functions
ConstVectorRange (const T &c)
Constructor.
ConstVectorRange (typename T::iterator b, typename T::iterator e)
Constructor.
ConstVectorRange (typename T::const_iterator b, typename T::const_iterator e)
Constructor.
ConstVectorRange (const VectorRange< T > &rhs)
Constructor.
bool operator== (const ConstVectorRange &rhs) const
comparison operator for equality
bool operator!= (const ConstVectorRange &rhs) const
comparison operator for inequality
T begin () const
access to the begin of the range
T end () const
access to the end of the range
bool empty () const
informs if there are any elements in the range
bool equal (const iterator_range &other) const
comparison for equality
bool operator== (const iterator_range &rhs) const
comparison operator for equality
bool operator!= (const iterator_range &rhs) const
comparison operator for inequality
Detailed Description
template<typename T>
struct Ogre::ConstVectorRange< T >
Predefined type.
Parameters:
T iterator type
compatility class for ConstVectorIterator
Definition at line 178 of file OgreIteratorRange.h.
Member Typedef Documentation
template<typename T> typedef T Ogre::iterator_range< T >::const_iterator [inherited]
typedef to fulfill container interface
Note:
there is no distinction between const_iterator and iterator.
Definition at line 110 of file OgreIteratorRange.h.
template<typename T> typedef T Ogre::iterator_range< T >::iterator [inherited]
typedef to fulfill container interface
Note:
there is no distinction between const_iterator and iterator.
Definition at line 102 of file OgreIteratorRange.h.
template<typename T> typedef iterator_range<T> Ogre::iterator_range< T >::type [inherited]
defines the real used type
type will be defined as Ogre::iterator_range if not used with boost
otherwise the type will be boost::iterator_range
Definition at line 117 of file OgreIteratorRange.h.
Constructor & Destructor Documentation
template<typename T > Ogre::ConstVectorRange< T >::ConstVectorRange (const T & c)
Constructor.
Remarks:
Provide a container to initialise.
Definition at line 185 of file OgreIteratorRange.h.
template<typename T > Ogre::ConstVectorRange< T >::ConstVectorRange (typename T::iterator b, typename T::iterator e)
Constructor.
Remarks:
Provide a start and end iterator to initialise.
Definition at line 193 of file OgreIteratorRange.h.
template<typename T > Ogre::ConstVectorRange< T >::ConstVectorRange (typename T::const_iterator b, typename T::const_iterator e)
Constructor.
Remarks:
Provide a start and end const_iterator to initialise.
Definition at line 201 of file OgreIteratorRange.h.
template<typename T > Ogre::ConstVectorRange< T >::ConstVectorRange (const VectorRange< T > & rhs)
Constructor.
Remarks:
Provide a VectorRange to initialise.
Definition at line 209 of file OgreIteratorRange.h.
Member Function Documentation
template<typename T> T Ogre::iterator_range< T >::begin () const [inherited]
access to the begin of the range
Definition at line 77 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::mBegin.
template<typename T> bool Ogre::iterator_range< T >::empty () const [inherited]
informs if there are any elements in the range
Definition at line 83 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::mBegin, and Ogre::iterator_range< T >::mEnd.
template<typename T> T Ogre::iterator_range< T >::end () const [inherited]
access to the end of the range
Definition at line 80 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::mEnd.
template<typename T> bool Ogre::iterator_range< T >::equal (const iterator_range< T > & other) const [inherited]
comparison for equality
Definition at line 86 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::mBegin, and Ogre::iterator_range< T >::mEnd.
Referenced by Ogre::VectorRange< T >::operator!=(), Ogre::ConstVectorRange< T >::operator!=(), Ogre::MapRange< T >::operator!=(), Ogre::ConstMapRange< T >::operator!=(), Ogre::iterator_range< T >::operator==(), Ogre::VectorRange< T >::operator==(), Ogre::ConstVectorRange< T >::operator==(), Ogre::MapRange< T >::operator==(), and Ogre::ConstMapRange< T >::operator==().
template<typename T> bool Ogre::iterator_range< T >::operator!= (const iterator_range< T > & rhs) const [inherited]
comparison operator for inequality
Definition at line 94 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::operator==().
template<typename T > bool Ogre::ConstVectorRange< T >::operator!= (const ConstVectorRange< T > & rhs) const
comparison operator for inequality
Definition at line 216 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::equal().
template<typename T> bool Ogre::iterator_range< T >::operator== (const iterator_range< T > & rhs) const [inherited]
comparison operator for equality
Definition at line 90 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::equal().
Referenced by Ogre::iterator_range< T >::operator!=().
template<typename T > bool Ogre::ConstVectorRange< T >::operator== (const ConstVectorRange< T > & rhs) const
comparison operator for equality
Definition at line 214 of file OgreIteratorRange.h.
References Ogre::iterator_range< T >::equal().
The documentation for this struct was generated from the following file:
OgreIteratorRange.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Sun Sep 2 2012 07:27:30